# Generated by Django 5.0.6 on 2024-07-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_review_options_alter_size_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='main.size', verbose_name='объём'),
        ),
    ]
